version: '3.8'

x-env: &env
  env_file:
    - .env

x-python: &python
  <<: *env
  image: ${NAMESPACE}/nw_server-${BUILD_VERSION}:latest

services:
  database:
    <<: *env
    image: postgres:16-alpine
    restart: always
    volumes:
      - prod_db_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    restart: always

  client:
    image: ${NAMESPACE}/nw_client-${BUILD_VERSION}:latest
    restart: always
    ports:
      - '3000:3000'

  server:
    <<: *python
    command: runserver
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - database
      - client

  bot:
    <<: *python
    command: runbot
    restart: always
    depends_on:
      - server

  celery:
    <<: *python
    command: runcelery
    restart: always
    depends_on:
      - redis

  nginx:
    image: ${NAMESPACE}/nw_nginx-${BUILD_VERSION}:latest
    restart: always
    ports:
      - '8765:80'
    depends_on:
      - client
      - server


volumes:
  prod_db_data:
