version: '3.8'

services:
  client:
    container_name: client
    build:
      context: client
      target: dev
    volumes:
      - ./client/src:/opt/src
      - ./client/public:/opt/public
    ports:
      - '3000:3000'
  tunnel:
    container_name: tunnel
    build: .dev/tunnel
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    depends_on:
      - cache
      - client
  server:
    container_name: server
    build: server
    volumes:
      - ./server:/opt/server
    env_file:
      - .env
    depends_on:
      - tunnel
  cache:
    container_name: cache
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - '6379:6379'
