version: '3.8'

x-env: &env
  env_file:
    - .env

x-python: &python
  <<: *env
  build:
    context: server
  depends_on:
    - client
    - database

services:
  database:
    <<: *env
    container_name: database
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - '5433:5432'

  client:
    container_name: client
    build:
      context: client
      target: dev
    volumes:
      - ./client/build:/app/build
      - ./client/src:/app/src
      - ./client/package.json:/app/package.json
      - ./client/package-lock.json:/app/package-lock.json
    ports:
      - '3000:3000'

  server:
    <<: *python
    container_name: server
    command: runserver
    volumes:
      - ./server:/opt/server
      - ./client/build:/opt/static/build
    ports:
      - '8000:8000'

  bot:
    <<: *python
    container_name: bot
    command: runbot
    restart: always
    volumes:
      # todo find out ? imports
      - ./server:/opt/server

  nginx:
    container_name: nginx
    image: nginx:1.25.2
    restart: always
    ports:
      - '8765:80'
    volumes:
      - .dev/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

  tunnel:
    <<: *env
    container_name: tunnel
    build: .dev/tunnel
    restart: always
    network_mode: host
    volumes:
      - .dev/tunnel/index.js:/app/index.js
    depends_on:
      - nginx


volumes:
  db_data:
