version: '3.8'

x-env: &env
  env_file:
    - .env

x-python: &python
  <<: *env
  build:
    context: server

services:
  database:
    <<: *env
    container_name: nw_database
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    container_name: nw_redis
    restart: always

  client:
    container_name: nw_client
    build:
      context: client
      target: dev
    volumes:
      - ./client/src:/app/src
      - ./client/package.json:/app/package.json
      - ./client/jsconfig.json:/app/jsconfig.json

  server:
    <<: *python
    container_name: nw_server
    command: runserver
    volumes:
      - ./server:/app
    depends_on:
      - redis
      - database
      - client

  bot:
    <<: *python
    container_name: nw_bot
    command: runbot
    restart: always
    volumes:
      - ./server:/app
    depends_on:
      - server

  celery:
    <<: *python
    container_name: nw_celery
    command: runcelery
    restart: always
    volumes:
      - ./server:/app
    depends_on:
      - redis

  nginx:
    image: nginx:1.25.0-alpine
    container_name: nw_nginx
    restart: always
    ports:
      - '8765:80'
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server


volumes:
  db_data:
