version: '3.8'

x-env: &env
  env_file:
    - .env

x-python: &python
  <<: *env
  build:
    context: server
  volumes:
    - ./server:/opt/server

services:
  client:
    container_name: client
    build:
      context: client
      target: dev
    volumes:
      - ./client/src:/opt/src
      - ./client/public:/opt/public
    ports:
      - '3000:3000'
  cache:
    <<: *env
    container_name: cache
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - '6379:6379'
  database:
    <<: *env
    container_name: database
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - '5433:5432'
  tunnel:
    <<: *env
    container_name: tunnel
    build: .dev/tunnel
    restart: always
    network_mode: host
    depends_on:
      - cache
      - client
  server:
    <<: *python
    container_name: server
    command: runserver
    depends_on:
      - database
      - cache
    ports:
      - '8000:8000'
  bot:
    <<: *python
    container_name: bot
    command: runbot
    depends_on:
      - server
      - tunnel

volumes:
  db_data:
