version: '3.8'

x-python-setup: &python-setup
  build:
    context: server
  volumes:
    - ./server:/opt/server
  env_file:
    - .env

services:
  client:
    container_name: client
    build:
      context: client
      target: dev
    volumes:
      - ./client/src:/opt/src
      - ./client/public:/opt/public
    ports:
      - '3000:3000'
  cache:
    container_name: cache
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - '6379:6379'
  database:
    container_name: database
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - '5433:5432'
  tunnel:
    container_name: tunnel
    build: .dev/tunnel
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    depends_on:
      - cache
      - client
    ports:
      - '8000:8000'
  server:
    <<: *python-setup
    container_name: server
    command: runserver
    depends_on:
      - database
      - cache
  bot:
    <<: *python-setup
    container_name: bot
    command: runbot
    depends_on:
      - server
      - tunnel

volumes:
  db_data:
