version: '3.8'

services:
  tunnel:
    container_name: tunnel
    build: .dev/tunnel
    restart: always
    network_mode: host
    volumes:
      - .dev/tunnel/index.js:/app/index.js
    env_file:
      - .env
