# Generated by Django 4.2.5 on 2023-10-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remind_in_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
