# Generated by Django 4.2.5 on 2023-10-07 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('events', '0002_event_remind_in_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tg_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='owner_of_events', to='bot.telegramuser', verbose_name='Calendar owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='tg_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='author_of_events', to='bot.telegramuser', verbose_name='Event creator'),
        ),
    ]
