# Generated by Django 4.2.5 on 2023-10-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(default='en')),
                ('is_bot', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
