# Generated by Django 4.2.5 on 2023-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='secret_key',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
